Repository CMPUT404W20/CMPUT404-project-socialdistribution, pull requests merged in 2020-03, with the labels that each got.

#76 Markdown Part 2
  package.json
  src/components/post/MakePost.jsx
  src/components/post/Post.jsx
  src/components/post/PostPreviewModal.jsx
  src/styles/post/MakePost.scss
  src/styles/post/PostPreviewModal.scss
  src/tests/components/post/MakePost.test.jsx
  src/tests/components/post/__snapshots__/MakePost.test.jsx.snap
  yarn.lock
Labels: UI

#85 Upload Image
  package.json
  src/components/post/MakePost.jsx
  src/components/post/PostPreviewModal.jsx
  src/components/post/UploadImageModal.jsx
  src/styles/post/MakePost.scss
  src/styles/post/UploadImageModal.scss
  src/tests/components/post/__snapshots__/MakePost.test.jsx.snap
  yarn.lock
Labels: Work in Progress

#122 108 create post
  package.json
  src/components/Homepage.jsx
  src/components/post/MakePost.jsx
  src/components/post/PostView.jsx
  src/services/PostService.jsx
  src/tests/components/post/__snapshots__/MakePost.test.jsx.snap
  yarn.lock
Labels: UI

#166 Endpoint hotfix
  backend/apiviews/friend_views.py
  backend/tests/test_author_api.py
  backend/tests/test_comment_api.py
  backend/tests/test_friends_api.py
  backend/tests/test_post_api.py
  backend/urls.py
  src/services/CommentService.jsx
  src/services/FriendService.jsx
  src/services/PostService.jsx
Labels: backend

#176 146 GitHub link ui
  src/components/NavigationBar.jsx
  src/components/profile/EditProfileModal.jsx
  src/components/profile/ProfileHeader.jsx
  src/components/profile/ProfilePage.jsx
  src/styles/profile/EditProfileModal.scss
Labels: UI

#151 Initial Host connect
  backend/apiviews/author_views.py
  backend/apiviews/friend_request_views.py
  backend/apiviews/post_views.py
  backend/models.py
  backend/serializers.py
  backend/server.py
  backend/tests/conftest.py
  backend/tests/test_author_api.py
  backend/tests/test_friends_api.py
  backend/urls.py
  backend/utils.py
Labels: backend

#180 added time in comment section
  src/components/post/Post.jsx
  src/styles/post/Post.scss
  src/tests/components/post/__snapshots__/Post.test.jsx.snap
Labels: UI

#178 Post response
  backend/migrations/0013_post_content_type.py
  backend/models.py
  backend/serializers.py
  src/tests/components/post/__snapshots__/Post.test.jsx.snap
Labels: backend

#194 Relative to absolute url for comment service
  src/services/CommentService.jsx
Labels: bug

#202 Add support for images
  backend/apiviews/post_views.py
  backend/models.py
  backend/tests/assets/test-image.png
  backend/tests/test_post_api.py
  src/components/Homepage.jsx
  src/components/post/EditablePost.jsx
  src/components/post/GithubPost.jsx
  src/components/post/Post.jsx
  src/components/post/PostPreviewModal.jsx
  src/components/post/PostView.jsx
  src/services/PostService.jsx
  src/tests/components/post/Post.test.jsx
  src/tests/components/post/__snapshots__/Post.test.jsx.snap
Labels: backend
