Repository CMPUT404W20/CMPUT404-project-socialdistribution, pull requests merged in 2020-04, with the labels that each got.

#215 Fix Author Endpoint
  backend/apiviews/author_views.py
  backend/urls.py
Labels: bug

#218 Privacy Selector
  package.json
  public/index.html
  src/components/post/EditablePost.jsx
  src/components/post/Post.jsx
  src/components/post/PostView.jsx
  src/components/post/PrivacySelectorModal.jsx
  src/components/post/UserSelector.jsx
  src/services/FriendService.jsx
  src/styles/post/Post.scss
  src/styles/post/PrivacySelectorModal.scss
  src/styles/post/UserSelector.scss
  src/tests/components/post/Post.test.jsx
  src/tests/components/post/__snapshots__/EditablePost.test.jsx.snap
  src/tests/components/post/__snapshots__/Post.test.jsx.snap
  yarn.lock
Labels: UI, connection

#207 search connection
  src/components/App.jsx
  src/components/Homepage.jsx
  src/components/NavigationBar.jsx
  src/components/PrivateRoute.jsx
  src/components/friends/FriendItem.jsx
  src/components/friends/FriendsPage.jsx
  src/components/notices/NoticeItem.jsx
  src/components/notices/NoticesPage.jsx
  src/components/post/Post.jsx
  src/components/profile/EditProfileModal.jsx
  src/components/profile/ProfileHeader.jsx
  src/components/profile/ProfilePage.jsx
  src/components/search/SearchItem.jsx
  src/components/search/SearchPage.jsx
  src/contexts/UserContext.jsx
  src/services/FriendService.jsx
  src/styles/profile/EditProfileModal.scss
  src/tests/components/SearchItem.test.jsx
  src/tests/components/__snapshots__/SearchItem.test.jsx.snap
  src/tests/components/friends/FriendItem.test.jsx
  src/tests/components/friends/FriendsPage.test.jsx
  src/tests/components/friends/__snapshots__/FriendItem.test.jsx.snap
  src/tests/components/notices/NoticeItem.test.jsx
  src/tests/components/notices/__snapshots__/NoticeItem.test.jsx.snap
  src/tests/components/post/Post.test.jsx
  src/tests/components/post/__snapshots__/Post.test.jsx.snap
Labels: connection

#224 fix context for profile page
  src/components/App.jsx
Labels: bug

#229 Make pagination work again
  backend/apiviews/post_views.py
Labels: bug

#231 update profile connection
  public/index.html
  public/static/manifest.json
  src/components/Login.jsx
  src/components/post/PostPreviewModal.jsx
  src/components/profile/EditProfileModal.jsx
  src/components/profile/ProfileHeader.jsx
  src/components/profile/ProfilePage.jsx
  src/services/AuthenticationService.jsx
  src/services/FriendService.jsx
  src/styles/profile/EditProfileModal.scss
  src/styles/profile/ProfileHeader.scss
  src/tests/components/__snapshots__/Login.test.jsx.snap
  src/tests/components/__snapshots__/ProfileHeader.test.jsx.snap
Labels: connection

#244 Allow "www" in the github url
  src/components/profile/EditProfileModal.jsx
Labels: bug
