Repository CMPUT404W20/CMPUT404-project-socialdistribution, pull requests merged in 2020-02, with the labels that each got.

#44 Update ESLint Config
  package.json
  src/components/Login.jsx
  src/services/Authentication.jsx
  src/styles/Login.scss
  src/tests/components/Login.test.jsx
  src/tests/components/__snapshots__/Login.test.jsx.snap
  src/tests/services/Authentication.test.jsx
  yarn.lock
Labels: quick fix

#43 Post Block UI
  .gitignore
  package-lock.json
  package.json
  src/components/post/PostBlock.jsx
  src/components/post/PostDropDown.jsx
  src/images/del-bin.svg
  src/images/demo-img.png
  src/images/edit-pencil.svg
  src/images/link.svg
  src/images/more-icon.svg
  src/styles/post/PostBlock.scss
  src/styles/post/PostDropDown.scss
  src/tests/components/post/PostBlock.test.jsx
  src/tests/components/post/PostDropDown.test.jsx
  src/tests/components/post/__snapshots__/PostBlock.test.jsx.snap
  src/tests/components/post/__snapshots__/PostDropDown.test.jsx.snap
  yarn.lock
Labels: Ready to Merge

#60 Navigation Bar + Homepage + Post Box
  package.json
  public/index.html
  src/components/App.jsx
  src/components/Homepage.jsx
  src/components/NavBar.jsx
  src/components/NavigationBar.jsx
  src/components/post/MakePost.jsx
  src/components/post/Post.jsx
  src/components/post/PostDropDown.jsx
  src/images/markdown-icon.svg
  src/styles/Homepage.scss
  src/styles/NavBar.scss
  src/styles/NavigationBar.scss
  src/styles/post/MakePost.scss
  src/styles/post/Post.scss
  src/styles/post/PostBlock.scss
  src/styles/post/PostDropDown.scss
  src/tests/components/NavBar.test.jsx
  src/tests/components/NavigationBar.test.jsx
  src/tests/components/__snapshots__/NavBar.test.jsx.snap
  src/tests/components/__snapshots__/NavigationBar.test.jsx.snap
  src/tests/components/post/MakePost.test.jsx
  src/tests/components/post/Post.test.jsx
  src/tests/components/post/PostDropDown.test.jsx
  src/tests/components/post/__snapshots__/MakePost.test.jsx.snap
  src/tests/components/post/__snapshots__/Post.test.jsx.snap
  src/tests/components/post/__snapshots__/PostBlock.test.jsx.snap
  src/tests/components/post/__snapshots__/PostDropDown.test.jsx.snap
Labels: UI
